### ISSUE TITLE
Authentication failed with XOAuth2 createConnection

### ISSUE THREAD

**Issue by tojibon** [pipedrive/inbox#108]
Hi,

After saving user access_token, gmail_address and refresh_token into database I tried to login and fetch emails with below codes sample:

`req.gmail_client = inbox.createConnection(false, "imap.gmail.com", {
                secureConnection: true,
                debug: true,
                auth:{
                    XOAuth2:{
                        user: loggedInUser.gmail_address,
                        clientId: CLIENT_ID,
                        clientSecret: CLIENT_SECRET,
                        refreshToken: loggedInUser.refresh_token,
                        accessToken: loggedInUser.access_token,
                        timeout: 3600
                    }
                }
            });`

Unfortunately its showing me errors like['in console']:

`Connection to server opened
SERVER: * OK Gimap ready for requests from 43.230.123.162 i6mb24402226oek
CLIENT: A1 CAPABILITY
SERVER: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH
SERVER: A1 OK Thats all she wrote! i6mb24402226oek
CLIENT: A2 AUTHENTICATE XOAUTH2 dXNlcj10b2ppYm9uMTVAZ21haWwuY29tAWF1dGg9QmVhcmVyIHlhMjkuQ2pIU0FvalpHTnhYSFRtODZ6QXRMRVhabjZfRW51S3VBRkg2MmZWdTFrd0VHbkwtOGZsZ1BUY3ZObjRpWE8yTWRXY0cBAQ==
SERVER: + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
CLIENT:
SERVER: A2 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
CLIENT: A3 AUTHENTICATE XOAUTH2 dXNlcj10b2ppYm9uMTVAZ21haWwuY29tAWF1dGg9QmVhcmVyIHlhMjkuQ2pIU0FrUVJWT0tjRVdWSmF2c0pQbjVZZGt4dTllWl9GZU9Fd2NUOXl2Mng4S1VxNFhza2JaT21vYWhZUmthQ2dJVEkBAQ==
SERVER: + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
CLIENT:
SERVER: A3 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
CLIENT: A4 AUTHENTICATE XOAUTH2 dXNlcj10b2ppYm9uMTVAZ21haWwuY29tAWF1dGg9QmVhcmVyIHlhMjkuQ2pIU0FzR0U1SzZ6Z1pXbVJxQnpjYTBfTDMwSGIwYm1NVkU5RDlIS1pMcjFPejBkODhlUUhka1E3dFA0UjVFZ3dJdlgBAQ==
SERVER: + eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
CLIENT:
SERVER: A4 NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)

Error: Authentication failed
    at IMAPClient._handlerTaggedLogin (.\node_modules\inbox\lib\client.js:868:25)
    at IMAPClient._currentRequest.callback (.\node_modules\inbox\lib\client.js:768:25)
    at IMAPClient._responseRouter (.\node_modules\inbox\lib\client.js:609:30)
    at IMAPClient._onServerResponse (.\node_modules\inbox\lib\client.js:542:10)
    at IMAPLineParser.EventEmitter.emit (events.js:95:17)
    at process._tickDomainCallback (node.js:459:13)`

Note: My access token generator scope was:
`scope: [
            'https://www.googleapis.com/auth/plus.me',
            'https://www.googleapis.com/auth/plus.profile.emails.read',
            'https://www.googleapis.com/auth/drive'
        ]`

and I am doing this with nodejs & sailsjs.

Thanks in advance

**Comment by tojibon** [comment]
**_To be noted:_** 

If I use this way with email address and password it seems working fine.
```javascript
req.gmail_client = inbox.createConnection(false, "imap.gmail.com", {
                secureConnection: true,
                debug: true,
                auth:{
                    user: MailInfo.email,
                    pass: MailInfo.pass
                }
            });
```

But I need that XOAuth2 based so I can can use access_token and refresh_token.

Thanks Again

**Comment by andris9** [comment]
The scope for IMAP and SMTP access is https://mail.google.com/

**Comment by tojibon** [comment]
Thanks for your reply,

I actually followed this example: https://github.com/pipedrive/inbox/blob/master/examples/xoauth2.js
