### ISSUE TITLE
Error: Authentication failed

### ISSUE THREAD

**Issue by benjamine** [pipedrive/inbox#91]
Hi, 
I've been using this package to access a mailbox from my machine without problems (OSX, node 0.10.32), it works perfectly.
But, when I try to do exactly the same in an ubuntu (headless) server (same node version: 0.10.32), authentication always fails (using same credentials, same script):

```
Error: Authentication failed
    at IMAPClient._handlerTaggedLogin (/home/ubuntu/orchard-mile-spec/node_modules/inbox/lib/client.js:868:25)
    at IMAPClient._currentRequest.callback (/home/ubuntu/orchard-mile-spec/node_modules/inbox/lib/client.js:768:25)
    at IMAPClient._responseRouter (/home/ubuntu/orchard-mile-spec/node_modules/inbox/lib/client.js:609:30)
    at IMAPClient._onServerResponse (/home/ubuntu/orchard-mile-spec/node_modules/inbox/lib/client.js:542:10)
    at IMAPLineParser.emit (events.js:95:17)
    at process._tickCallback (node.js:419:13)
```

the auth method is plain email & password.
I'm a bit lost, any clues on how to solve it? I can provide more debugging info as needed,
thanks!

**Comment by benjamine** [comment]
nevermind, I logged the `error.errorLog` and it was just google wanting me to do some security checks, thanks for this lib!!
